"""Auto migration

Revision ID: 2ab424dc0028
Revises: 2b746950959e
Create Date: 2025-11-17 14:32:14.787655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab424dc0028'
down_revision = '2b746950959e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
