"""add color and emojis to the tutorials table

Revision ID: 3d696fc8d92a
Revises: e9b6c65aa089
Create Date: 2025-11-24 16:03:25.861275

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3d696fc8d92a"
down_revision = "e9b6c65aa089"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tutorials",
        sa.Column(
            "category_emoji", sa.String(length=10), nullable=False, server_default="🎨"
        ),
    )
    op.add_column(
        "tutorials",
        sa.Column(
            "category_color",
            sa.String(length=7),
            nullable=False,
            server_default="#FF6B6B",
        ),
    )
    op.add_column(
        "tutorials",
        sa.Column(
            "subject_emoji", sa.String(length=10), nullable=False, server_default="✏️"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("tutorials", "subject_emoji")
    op.drop_column("tutorials", "category_color")
    op.drop_column("tutorials", "category_emoji")
    # ### end Alembic commands ###
