"""add bilingual titles for the stories table

Revision ID: 8bd8d4f73c6f
Revises: c42c8e2617e3
Create Date: 2025-12-03 15:54:56.737204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd8d4f73c6f'
down_revision = 'c42c8e2617e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('title_en', sa.String(length=200), nullable=False))
    op.add_column('stories', sa.Column('title_de', sa.String(length=200), nullable=False))
    op.drop_column('stories', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('stories', 'title_de')
    op.drop_column('stories', 'title_en')
    # ### end Alembic commands ###
