"""Add new table edit_options

Revision ID: 93f057d0e0e6
Revises: 49a19c546e47
Create Date: 2025-11-20 13:39:53.638923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93f057d0e0e6'
down_revision = '49a19c546e47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edit_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('title_en', sa.String(length=100), nullable=False),
    sa.Column('title_de', sa.String(length=100), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('description_de', sa.Text(), nullable=False),
    sa.Column('prompt_en', sa.Text(), nullable=False),
    sa.Column('prompt_de', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edit_options_category'), 'edit_options', ['category'], unique=False)
    op.create_index(op.f('ix_edit_options_id'), 'edit_options', ['id'], unique=False)
    op.create_index(op.f('ix_edit_options_subject'), 'edit_options', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_edit_options_subject'), table_name='edit_options')
    op.drop_index(op.f('ix_edit_options_id'), table_name='edit_options')
    op.drop_index(op.f('ix_edit_options_category'), table_name='edit_options')
    op.drop_table('edit_options')
    # ### end Alembic commands ###
