"""Add bilingual category and subject fields and create relationship between tutorials and edit_options tables

Revision ID: c42c8e2617e3
Revises: 3d696fc8d92a
Create Date: 2025-11-25 12:42:55.442827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c42c8e2617e3'
down_revision = '3d696fc8d92a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('edit_options', sa.Column('tutorial_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_edit_options_category'), table_name='edit_options')
    op.drop_index(op.f('ix_edit_options_subject'), table_name='edit_options')
    op.create_index(op.f('ix_edit_options_tutorial_id'), 'edit_options', ['tutorial_id'], unique=False)
    op.create_foreign_key(None, 'edit_options', 'tutorials', ['tutorial_id'], ['id'])
    op.drop_column('edit_options', 'category')
    op.drop_column('edit_options', 'subject')
    op.add_column('tutorials', sa.Column('category_en', sa.String(length=100), nullable=False))
    op.add_column('tutorials', sa.Column('category_de', sa.String(length=100), nullable=False))
    op.add_column('tutorials', sa.Column('subject_en', sa.String(length=100), nullable=False))
    op.add_column('tutorials', sa.Column('subject_de', sa.String(length=100), nullable=False))
    op.drop_index(op.f('ix_tutorials_category'), table_name='tutorials')
    op.create_index(op.f('ix_tutorials_category_de'), 'tutorials', ['category_de'], unique=False)
    op.create_index(op.f('ix_tutorials_category_en'), 'tutorials', ['category_en'], unique=False)
    op.drop_column('tutorials', 'category')
    op.drop_column('tutorials', 'subject')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tutorials', sa.Column('subject', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('tutorials', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tutorials_category_en'), table_name='tutorials')
    op.drop_index(op.f('ix_tutorials_category_de'), table_name='tutorials')
    op.create_index(op.f('ix_tutorials_category'), 'tutorials', ['category'], unique=False)
    op.drop_column('tutorials', 'subject_de')
    op.drop_column('tutorials', 'subject_en')
    op.drop_column('tutorials', 'category_de')
    op.drop_column('tutorials', 'category_en')
    op.add_column('edit_options', sa.Column('subject', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('edit_options', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'edit_options', type_='foreignkey')
    op.drop_index(op.f('ix_edit_options_tutorial_id'), table_name='edit_options')
    op.create_index(op.f('ix_edit_options_subject'), 'edit_options', ['subject'], unique=False)
    op.create_index(op.f('ix_edit_options_category'), 'edit_options', ['category'], unique=False)
    op.drop_column('edit_options', 'tutorial_id')
    # ### end Alembic commands ###
