"""add_reset_code_to_users

Revision ID: e9b6c65aa089
Revises: 6446f125b5f4
Create Date: 2025-11-24 15:28:11.275704

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e9b6c65aa089"
down_revision = "6446f125b5f4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add reset_code columns first (most important)
    op.add_column("users", sa.Column("reset_code", sa.String(length=6), nullable=True))
    op.add_column(
        "users", sa.Column("reset_code_expires_at", sa.DateTime(), nullable=True)
    )
    # Note: Skipping ALTER COLUMN operations as they may fail on some database states
    # The timestamp columns are already properly configured in the database
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only drop the reset_code columns
    op.drop_column("users", "reset_code_expires_at")
    op.drop_column("users", "reset_code")
    # ### end Alembic commands ###
